export const errorCodes = {
  NAME_REQUIRED: 'NAME_REQUIRED',
  DESCRIPTION_REQUIRED: 'DESCRIPTION_REQUIRED',
  PEOPLE_EMAIL_REQUIRED: 'PEOPLE_EMAIL_REQUIRED',
  EVIDENCE_ID_REQUIRED: 'EVIDENCE_ID_REQUIRED',
  EVALUATOR_ID_REQUIRED: 'EVALUATOR_ID_REQUIRED',
  PEOPLE_ID_REQUIRED: 'PEOPLE_ID_REQUIRED',
  NON_NUMERIC_VALUE: 'NON_NUMERIC_VALUE'
}
